exports.LOGIN = 'LOGIN';
exports.REGISTER_COGNITO = 'REGISTER_COGNITO';
exports.REGISTER = 'REGISTER';
exports.HOME = 'HOME';
exports.MEDICAL_DECLARATION = 'MEDICAL_DECLARATION';

exports.LAYOUT = 'LAYOUT';
